services:
  # cURL client for Buzz
  buzz.client.curl:
    class:  Buzz\Client\Curl
    public: false
    calls:
      - [setVerifyPeer, [false]]

  # Buzz browser
  buzz.browser:
    class:     Buzz\Browser
    arguments: ['@buzz.client.curl']

  stock.export.factory:
    class:    IK\StockBundle\Model\Export\Factory
    calls:
      - [setBuzzBrowser, ['@buzz.browser']]
      - [setEntityManager, ['@doctrine.orm.entity_manager']]